//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Homework", Namespace="http://schemas.datacontract.org/2004/07/Homework")]
    public partial class Homework : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StudentField;
        
        private string TaskField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Student
        {
            get
            {
                return this.StudentField;
            }
            set
            {
                this.StudentField = value;
            }
        }
            
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Task
        {
            get
            {
                return this.TaskField;
            }
            set
            {
                this.TaskField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IHomeworkService")]
public interface IHomeworkService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeworkService/Do", ReplyAction="http://tempuri.org/IHomeworkService/DoResponse")]
    string Do(Homework.Homework homework);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHomeworkService/Do", ReplyAction="http://tempuri.org/IHomeworkService/DoResponse")]
    System.Threading.Tasks.Task<string> DoAsync(Homework.Homework homework);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHomeworkServiceChannel : IHomeworkService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HomeworkServiceClient : System.ServiceModel.ClientBase<IHomeworkService>, IHomeworkService
{
    
    public HomeworkServiceClient()
    {
    }
    
    public HomeworkServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HomeworkServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HomeworkServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HomeworkServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string Do(Homework.Homework homework)
    {
        return base.Channel.Do(homework);
    }
    
    public System.Threading.Tasks.Task<string> DoAsync(Homework.Homework homework)
    {
        return base.Channel.DoAsync(homework);
    }
}
